### ISSUE TITLE
Image and/or Demo

### ISSUE THREAD

**Issue by Hirse** [ovsleep/bootstrap-switch#3]
Could you include a screenshot into your README?

Ideally, a demo would also be great, especiallly since the http://www.bootstrap-switch.org/ page doesn't load for me right now.

**Comment by ovsleep** [comment]
Sorry, wasn't around for a while. I'm working on a demo page now.

**Comment by ovsleep** [comment]
Here's a link to the [demo](https://bootstrap-switch.herokuapp.com/)
Also added to the README.
Thanks for the recommendation.

**Comment by Hirse** [comment]
Cool, looks good. 👍
