### ISSUE TITLE
Change event

### ISSUE THREAD

**Issue by somnathswami** [ovsleep/bootstrap-switch#4]
I have successfully implement this component but i cannt trace its change event in my typescript file

i am using 
   <switch [status]=false [onText]="onText" [offText]="offText" [onColor]="onColor" [offColor]="offColor" [size]="size" (change)="onSwitchChange();">
code and written definition onSwitchChange() in typescript file but it wont work

**Comment by ovsleep** [comment]
The reason this isn't working is that the name of the event is "statusChange". I should've used just change though. 
Anyway, if you do it like this should work:

`<switch [status]=false [onText]="onText" [offText]="offText" [onColor]="onColor" [offColor]="offColor" [size]="size" (statusChange)="onSwitchChange()">`

Notice the change form **(change)** to **(statusChange)**

**Comment by somnathswami** [comment]
Hello Guillermo Pérez,

Thanks it really helps me

Regards
Somnath
